### ISSUE TITLE
os.system("clear")

### ISSUE THREAD

**Issue by brunobaring-farmsteadapp** [Rafabaring/tic_tac_toe#1]
`os.system("clear")`
o q é isso? É necessário?

**Comment by Rafabaring** [comment]
Isso é necessário para limpar a tela do terminal.
Sempre que "print" o "tabuleiro" vai imprimir em uma tela nova e limpa

**Comment by brunobaring-farmsteadapp** [comment]
ah saquei. esse `os.system()` é pra executar comandos do terminal entao ne. legal
