### ISSUE TITLE
inicializacao do array cells

### ISSUE THREAD

**Issue by brunobaring-farmsteadapp** [Rafabaring/tic_tac_toe#2]
```
self.cells = [" "
                     ," ", " ", " "
                     ," ", " ", " "
                     ," ", " ", " "]
```
Deve existir um jeito mais elegante para inicializar isso no Python. Joguei no google aqui e achei `self.cells = [" "] * 10`. Mais elegante, nao?

**Comment by Rafabaring** [comment]
Boa. Vou fazer essa modificação
