### ISSUE TITLE
def check_score

### ISSUE THREAD

**Issue by brunobaring-farmsteadapp** [Rafabaring/tic_tac_toe#5]
o `check_score` poderia ser otimizado. É um código q testa todas as possibilidades, sem necessidade, aumentando o custo e manutenção.

por exemplo, se vc já verificou q nao tem `X` marcado no canto top left, nao faz sentido verificar se ele ganhou diagonalmente, verticalmente ou horizontalmente naquele ponto.

**Comment by Rafabaring** [comment]
Tem razão.

Como eu sabia que o jogo não ia crescer muito dai, eu deixei não otimizado mesmo. Mas se eu fosse elaborar mais, certamente faria uma forma mais otimizada
