### ISSUE TITLE
while True

### ISSUE THREAD

**Issue by brunobaring-farmsteadapp** [Rafabaring/tic_tac_toe#6]
Essa aqui foi polêmica. Eu não acho q precise fazer esse while true, pelo tipo de jogo. Joguei a bomba aqui pra galera do escritorio e nego achou q precisa sim.

Eu acho q nao precisa pq o jogo sempre age de acordo com um input do teclado, e por isso vc consegue alterar o estado do `Board`.

Nego aqui acha q vc precisa do `while True` para recuperar o estado do tabuleiro.

**Comment by Rafabaring** [comment]
Eu coloquei o `while True` por esse motivo mesmo. Recuperar o estado do tabuleiro

**Comment by Rafabaring** [comment]
Eu mostrei pra um colega do trabalho e acho que ele tb não curtiu não.

A verdade é que while True realmente não é a melhor opção por que o jogo não ta acabando. Ta meio que num loop infinito. Tem espaço pra melhorar aqui. Vlw!

**Comment by brunobaring-farmsteadapp** [comment]
reza a lenda q todo compilador no fundo no fundo tem um `while true` desses internamente. vai saber.
